### ISSUE TITLE
Deprecated getConfiguration().locale;

### ISSUE THREAD

**Issue by joelrose2** [gokberkbar/locale_plus#15]
Please release an updated version of this terrific packages that addresses two issues:

1.	Flutter reports that it is using a deprecated element:
C:\Users\xyz\AppData\Local\Pub\Cache\hosted\pub.dev\locale_plus-1.6.0+1\android\src\main\java\com\gokberkbar\locale_plus\LocalePlusPlugin.java:50: warning: [deprecation] locale in Configuration has been deprecated
Locale currentLocale = mContext.getResources().getConfiguration().locale;

2.	The package seems to be preventing Flutter from upgrading to the latest version of intl package (0.20.2).

Thank you!

**Comment by gokberkbar** [comment]
I will fix it this week sorry for late response

**Comment by gokberkbar** [comment]
Just released version 1.7.0. It should be fixed

**Comment by joelrose2** [comment]
Hi. Latest version still showing this on compile (Flutter Channel stable, 3.32.2, on Microsoft Windows [Version 10.0.26100.4349], locale en-US):

```
C:\Users\x\AppData\Local\Pub\Cache\hosted\pub.dev\locale_plus-1.7.0\android\src\main\java\com\gokberkbar\locale_plus\LocalePlusPlugin.java:56: warning: [deprecation] locale in Configuration has been deprecated
      currentLocale = config.locale;
                            ^
```

**Comment by gokberkbar** [comment]
> Hi. Latest version still showing this on compile (Flutter Channel stable, 3.32.2, on Microsoft Windows [Version 10.0.26100.4349], locale en-US):
> 
> ```
> C:\Users\x\AppData\Local\Pub\Cache\hosted\pub.dev\locale_plus-1.7.0\android\src\main\java\com\gokberkbar\locale_plus\LocalePlusPlugin.java:56: warning: [deprecation] locale in Configuration has been deprecated
>       currentLocale = config.locale;
>                             ^
> ```

I will take a look at it
